//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leccion4_Utilizando_Bloqueos_WcfSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
